name: Matrix Build

permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - master

jobs:
  discover:
    name: "Discover"
    runs-on: ubuntu-latest

    steps:
      - name: Discovering Resources
        run: echo "Discovering..."

  matrix:
    name: "${{ matrix.environment.name }}"
    runs-on: ubuntu-latest
    needs: discover

    strategy:
      fail-fast: false
      matrix:
        environment:
          - name: "foo"
          - name: "bar"
          - name: "zaz"

    steps:
      - name: Calculate stuff
        run: |
          set +eoux

          if [ "${{ matrix.environment.name }}" = "bar" ]; then
            echo "❌ error"
            exit 1
          else
            echo "✅ all good"
          fi

  final:
    name: " Topics - ${{ matrix.environment.name }}"
    runs-on: ubuntu-latest
    needs: matrix

    steps:
      - name: Final
        run: echo "final"
