name: build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  file-changes:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: read
    outputs:
      match: ${{ steps.filter.outputs.match }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        if: github.event_name != 'pull_request'
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            match:
              - '.github/workflows/path-filter.yml'
              - '*'

  build-go-client:
    runs-on: ubuntu-24.04
    needs: file-changes
    if: ${{ needs.file-changes.outputs.match == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Foo
        run: echo "FOO"
